FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app/ml_service

RUN pip install --no-cache-dir \
    elasticsearch==8.14.0 \
    psycopg2-binary==2.9.9

COPY scripts/export_ml_scores_to_elasticsearch.py ./scripts/export_ml_scores_to_elasticsearch.py

CMD ["python", "scripts/export_ml_scores_to_elasticsearch.py"]
