input {
  file {
    id => "raw_log_input"
    path => ["/usr/share/logstash/host_uploads/raw/*/*/*"]
    exclude => ["*.zip","*.gz","*.png","*.jpg","*.jpeg","*.pdf","*.7z","*.tar"]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb_raw"
    mode => "tail"
    discover_interval => 2
    stat_interval => 1
    codec => plain
  }
}

filter {
  mutate { add_field => { "source_path" => "%{[log][file][path]}" } }
  grok {
    match => { "source_path" => ".*/raw/%{DATA:application_key}/%{DATA:component_name}/%{DATA:stored_file_name}$" }
    tag_on_failure => ["path_parse_failed"]
  }
  mutate { lowercase => ["application_key", "component_name"] }
}

output {
  elasticsearch {
    index => "lvlogs-%{[application_key]}-%{[component_name]}-%{+YYYY.MM.dd}"
    hosts => ["https://es01:9200"]
    user => "elastic"
    password => "changeme123"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
  }
  stdout { codec => rubydebug }
}
